language: php
php: '5.6'
install: composer install
script: php run.php
before_deploy:
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- export GIT_TAG=v1.0.$TRAVIS_BUILD_NUMBER
- git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER
  [ci skip]"
- git push -q https://${GH_TOKEN}@github.com/Stevie-Ray/referrer-spam-blocker --tags
- ls -aR
deploy:
  provider: releases
  api_key:
    secure: "${GH_TOKEN}"
  skip_cleanup: true
  on:
    tags: false
    all_branches: true
branches:
  except: "/^*-v[0-9]/"
env:
  global:
  - secure: Ss39wyKYXAW3m2+VYavn8zV3N9FySlydBzea9Jjq5zc49AmgE2ngaezEbVYOsePIKoKc0+Scg8O5hlm0D4GEPqDM361ON9vopOXYRtkcgHzlAaRD2k9tvV28phzKtmYBMfnXNiJgYqRof1KUHfyN4tcoGGMbhWqLpUZN/Qs87YI=
notifications:
  email: false
